### ISSUE TITLE
Kernel died in networkvisualization-tensorflow.ipynb

### ISSUE THREAD

**Issue by pjpjq** [madalinabuzau/CS231n-Convolutional-Neural-Networks-for-Visual-Recognition#1]
I tried the same way like you: comment the lines of raising "You need to download squeezenet error"
but still not working. The kernel died in the next cell. Any ideas?

**Comment by madalinabuzau** [comment]
Did you download the SqueezeNet  model with the bash script get_squeezenet_tf.sh?

**Comment by pjpjq** [comment]
Yeah.

**Comment by pjpjq** [comment]
Did you change the 3 downloaded files?

**Comment by madalinabuzau** [comment]
No, I didn't modify them. Whenever my kernel dies it is usually because it runs out of memory. Maybe is this the case for you as well? Let me know if this is the case.... You can try closing all the other assignments.

**Comment by pjpjq** [comment]
How do I check if it is the memory problem...? I am using a 4GB RAM Mac.

**Comment by madalinabuzau** [comment]
If you are using Windows I believe you can use the Task Manager? For ubuntu you can use gnome-system-monitor. The easiest way would be to close all the other assignments if they're opened (with 'Close and Halt Notebook') and try again working solely with that assignment opened. Let me know if you managed to solve it! Good luck and don't give up, you're very close to finishing the course :)!
