### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Gaurav1302** [madalinabuzau/CS231n-Convolutional-Neural-Networks-for-Visual-Recognition#2]
Hey! facing this issue, would be great if you can help. Thanks!
![34339726-fc8cf7fe-e99d-11e7-829e-9e1fa3103b17](https://user-images.githubusercontent.com/32873995/34410764-7d632266-ebf8-11e7-9d50-c463513824e7.png)

**Comment by madalinabuzau** [comment]
Hi! From my understanding, the library _'past'_ is used to bring some Python 2 functionality to Python 3. You can find more info about this library _[here](https://pypi.python.org/pypi/past/)_ . To install this module, you have to run _'pip install future'_ in the terminal. Alternatively, if you do not want to install this module you can erase _'from past.builtins import xrange'_ and replace _'xrange'_ with _'range'_ which is the Python 3 version of this function. Hope this helps!

**Comment by Gaurav1302** [comment]
Hey! Thanks for writing. Tried both the things, but the same message pops up. future was already installed, tried uninstalling and installing. Still doesn't work!

**Comment by Gaurav1302** [comment]
Hey, changing xrange to range, worked for me, thanks! @madalinabuzau

**Comment by madalinabuzau** [comment]
Glad to hear you managed to solve it. Good luck with the further assignments :+1: !
